### ISSUE TITLE
SurveyLFs.fn fails when zero fish of a given sex

### ISSUE THREAD

**Issue by taylori** [nwfsc-assess/nwfscSurvey#10]
The line
```
names(temp) <- c("Trawl_id","Length_cm","numM")
```
failed when trying to look at length comps for `Name = "Pacific halibut"` due to NULL result for
```
TdatL.lengths[["M"]][,c("Trawl_id","Length_cm","num")]
```

**Comment by CWetzel** [comment]
Corrected to handle data sets where only a few fish are sexed
