### ISSUE TITLE
If no area swept

### ISSUE THREAD

**Issue by kellijohnson** [nwfsc-assess/nwfscSurvey#15]
https://github.com/nwfsc-assess/nwfscSurvey/blob/f2fd9a895c021e8e6486ac261a32771a8af05029/R/PullCatch.fn.R#L172

I am getting an error here when there are NA values for area swept. I think the following code fixes it
```
Out[noArea,"Area_Swept_ha"] <- mean(Out$Area_Swept_ha, trim = 0.05, na.rm = TRUE)
```

**Comment by James-Thorson** [comment]
sure, imputing missing values for area-swept seems like one solution.  someone might also want to notify Beth / Todd Hay that the data should be added to the database
