### ISSUE TITLE
cap GetN.fn sample size estimates at number of fish?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscSurvey#19]
I ran the GetN.fn for Big Skate as part of the following commands
```
catch.Tri.BS <- PullCatch.fn(Name = "big skate", SurveyName = "Triennial")
bio.Tri.BS   <- PullBio.fn(Name = "big skate", SurveyName = "Triennial")
n = GetN.fn(dir=dir, dat = bio.Tri.BS$Lengths, type = "length",
    species = "others", printfolder = "Triennial_comps")
```
which produced the table below, including the use of the the "others" species formula which has "The effN sample size is calculated as 2.38 multiplied by the number of tows in each year." However, there were fewer than 2.38 Big Skate lengths sampled per tow where they occurred, so the `Sample_Size` column is bigger `All_Fish`. It might be good to cap the `Sample_Size` estimate in cases like this.

Year | Tows | All_Fish | Sexed_Fish | Unsexed_Fish | Sample_Size
-- | -- | -- | -- | -- | --
1998 | 2 | 3 | 0 | 3 | 4
2001 | 43 | 84 | 80 | 4 | 102
2004 | 39 | 100 | 100 | 0 | 92

**Comment by James-Thorson** [comment]
What algorithm are you using to generate the inoit sample size? Bootstrap I assume, or my formula for having equal variance to a naive "design-like" estimator?

**Comment by taylori** [comment]
@James-Thorson nothing so fancy. It's the piecewise linear combination of N fish and N tows from:
Stewart, I.J. and O.W Hamel 2014. Bootstrapping of sample size for legth- or age-composition data used in stock assessment Canadian Journal of Fishery and Aquatic Science, 71: 581-588.

I think that paper recommending doing new bootstraps for any new species, but we've never taken the time to do that.

**Comment by CWetzel** [comment]
Commit 2ece7e36383ddb85b15cd6fb4e56419775582333 has been pushed to the main branch to address this issue. If the calculated input sample size exceeds the total number of fish sampled, the value is replace to be equal to the number of fish.
