### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by taylori** [nwfsc-assess/nwfscSurvey#2]
Adding roxygen comments to the functions would allow automatic generation of .Rd files via the devtools::document function: http://r-pkgs.had.co.nz/man.html

Other forms of documentation could be useful too.

**Comment by taylori** [comment]
I just documented one simple function and it took a little while so I have a renewed respect for the size of this undertaking.

Note that if roxygen is used, existing documentation in .Rd files (such as https://github.com/nwfsc-assess/nwfscSurvey/blob/master/man/StrataAreas.fn.Rd) should be converted into the header of the .R file. 
Also, error on package install "unknown macro '\begin'" can likely be removed by replacing "\begin{verbatim}" should be replaced by "\preformatted{".

**Comment by CWetzel** [comment]
The documentation has been improved and a vignette is also now available for the code. This update is currently located on the development branch and can be testing using this command:
devtools::install_github("nwfsc-assess/nwfscSurvey", ref = "development", build_vignettes = TRUE)
