### ISSUE TITLE
SurveyLFs.fn depends on missing "Lengths" variable

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscSurvey#20]
To test the impact of `sexRatioStage` in `SurveyLFs.fn`, I tried it for the first time with `sexRatioStage = 1` and got the following error:
```
Error in SexRatio.fn(x = datB, sexRatioStage = sexRatioStage, sexRatioUnsexed = sexRatioUnsexed,  : 
  object 'Lengths' not found
```
which seems to be coming from line 56 of `SexRatio.fn` expecting a variable `Lengths` which gets created in `SurveyLFs.fn` but not passed to `SexRatio.fn`.

There's no rush to fix this as I don't think the `sexRatioStage` input wouldn't sort out my comps anyway, which is more likely the result of the Triennial survey sampling for Big Skate being rotten such that any expansion will lead to strange and noisy comps.

**Comment by CWetzel** [comment]
@taylori thanks for catching this issue.  I have corrected the issue (c426d7b558c983537359fa6e5c17209ea8d2afac and 9b3fed061dd5238f52640c8c4d21860caeef8c07) in the main branch.  However, I was unable to recreate the situation where you would go into this loop to fill in the sex ratios.  Please test it and let me know if you are still having difficulties here.
