### ISSUE TITLE
AFSC Slope Units

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/nwfscSurvey#27]
https://github.com/nwfsc-assess/nwfscSurvey/blob/b6103f7f3b0f9d28250a4aaae00272a23fecd709/R/Format.AKSlope.fn.R#L43

@iantaylor-NOAA Can you double check these units?  I can never figure this out.  It does not "seem" right but it creates cpue values that appear to be in the same units as other data sets.  Thank you.

**Comment by iantaylor-NOAA** [comment]
This looks right to me. There are 1 km^2 = 100 ha so the catch per the larger area should be 100 times bigger than the catch per the smaller area.
