### ISSUE TITLE
foreign_hauls.csv is missing; can't exclude foreign hauls.

### ISSUE THREAD

**Issue by andi-stephens** [nwfsc-assess/nwfscSurvey#3]
foreign_hauls.csv is missing from package.

**Comment by taylori** [comment]
I just copied AFSCforeign_hauls.rda from the [nwfscDeltaGLM](https://github.com/nwfsc-assess/nwfscDeltaGLM) package.

An example usage from https://github.com/James-Thorson/VAST/blob/master/examples/West_Coast_Triennial_example_2017.R is

```
# Exclude foreign hauls
data(AFSCforeign_hauls, package = "nwfscDeltaGLM")
Exclude = which(Data_Set$HAULJOIN %in% AFSCforeign_hauls$HAULJOIN)
```
which could now presumably have `package = "nwfscDeltaGLM"` removed, or replaced with `package = "nwfscSurvey"` for use in this package.

However, examples and whatnot would all need to be revised to change the name and load process from foreign_hauls.csv. Or we could save the .rda file as a CSV called foreign_hauls.csv.

**Comment by taylori** [comment]
To clarify, in commit 4248f46 I copied  AFSCforeign_hauls.rda from the nwfscDeltaGLM package into this package's "examples" folder: [https://github.com/nwfsc-assess/nwfscSurvey/tree/master/data](https://github.com/nwfsc-assess/nwfscSurvey/tree/master/data).

**Comment by andi-stephens** [comment]
It could be included in a "data" folder within the package, and would then
be available without having to load it separately.

**Comment by kellijohnson** [comment]
@CWetzel should we write some code to exclude foreign and water hauls?

**Comment by CWetzel** [comment]
@kellijohnson The database team is currently working on creating an identifier for both foreign and water hauls which will allow for exclusion.  This is scheduled to be completed by the end of the year, well ahead of peak assessment season.  Based on that I have opted to not take the time to implement temporary clunky code to do this but rather have provided a simple warning to the user that these data are currently not being included.

**Comment by kellijohnson** [comment]
Thanks, waiting sounds like a terrific solution to me.

**Comment by CWetzel** [comment]
Commit https://github.com/nwfsc-assess/nwfscSurvey/commit/1445e9d04747688d8c1c57d22227aa3e7656f955 fixes this issue for the Triennial survey
