### ISSUE TITLE
package installation issues

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscSurvey#32]
I had two installation issues with this package. Neither is really our fault but users should be aware of them in case they have the same problems.

First was `Error: (converted from warning) package 'dplyr' was built under R version 4.0.3` which is discussed [here](https://github.com/r-lib/remotes/issues/403#issuecomment-769283882) with a not-ideal solution to first run `Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")`. 

Second, the dependency of `PlotMap.fn()` on `rnaturalearthhires` caused an error where the package suggests a method of installation that doesn't work. As discussed in both issues on that package (e.g. https://github.com/ropensci/rnaturalearthhires/issues/2), it should be manually installed via `devtools::install_github("ropensci/rnaturalearthhires")` instead of the command that gets suggested.

**Comment by ericward-noaa** [comment]
I ran into the first of these a couple weeks ago when digging into the haul data.

I think the dependencies for the package need to be updated. Happy to do that, and was also going to suggest adding a GitHub actions badge so we'd know when things were not building right in the future. I've been converting my other packages to using that & it's pretty seamless. Any objections?

**Comment by chantelwetzel-noaa** [comment]
@ericward-noaa That would be great.  I tried creating a badge via travis a while ago and was never able to sort it out.  I think this would be really useful and hopefully if I see how you did it, I can maintain this in the future.

**Comment by iantaylor-NOAA** [comment]
@ericward-noaa, thanks for volunteering. I assume that before you get a badge, you need to set up the GitHub Action, which would be even better. @k-doering-NOAA switched the r4ss package from Travis-CI to GitHub Actions for the testthat tests and indeed things run faster and smoother now, so I support you making the switch here as well.

We should also consider adding automatic tests via GitHub Actions for the other nwfsc-assess repositories as well. A quick look indicates:
- [sa4ss](https://github.com/nwfsc-assess/sa4ss) has testing via GitHub Actions (nice work @kellijohnson-NOAA!)
- [nwfscSurvey](https://github.com/nwfsc-assess/nwfscSurvey) has testing via Travis (nice work @chantelwetzel-noaa!)
- [geostatistical_delta-GLMM](https://github.com/nwfsc-assess/geostatistical_delta-GLMM) has testing via Travis
- [VASTWestCoast](https://github.com/nwfsc-assess/VASTWestCoast) has tests that can be run locally, but no automation via Travis or GitHub Actions
- [nwfscAgeingError](https://github.com/nwfsc-assess/nwfscAgeingError) has a `tests` folder that I added 2 years ago, but I don't see any tests associated with it

The other 7 packages have nothing. I presume that the setup of a R-CMDcheck action is pretty straightforward so we should think about adding that to all packages within this organization, perhaps by copying whatever @ericward-noaa adds to this one.

**Comment by k-doering-NOAA** [comment]
That sounds like a great plan, like @ericward-noaa said, the R CMD check github action workflow seems to be easy to copy/paste to other repositories and get working quickly. I'll also note that Travis-CI.org is going offline (or maybe already has), so it would be good to switch the pkgs over to github actions.

Happy to help set up github actions, if another person helping out would be useful. Let me know!

**Comment by ericward-noaa** [comment]
Just in case you all want to adopt the same thing for other packages, I removed the Travis files that were in this repo, and generated the Github action badge via 

`usethis::use_github_action_check_standard()`

There's a lot of customization that could be done with these, detailed in places like
https://ropenscilabs.github.io/actions_sandbox/packageci.html
https://usethis.r-lib.org/reference/github_actions.html

There are some limits to be aware of, especially in thinking about integrating these with all of the other packages,
https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration

I can at least speak for the packages I'd helped with, but there's things like 'nwfscDeltaGLM' -- the code works fine, and hasn't been changed in years -- so there's probably no reason to remove the Travis badge or switch it over to Github actions

**Comment by iantaylor-NOAA** [comment]
Thanks @ericward-noaa. I wasn't aware of the `usethis` function.

As @k-doering-NOAA mentioned previously, Travis is changing in ways that may make the existing badge not work (see banner at the top of https://travis-ci.org/github/nwfsc-assess/nwfscDeltaGLM). I agree that updating nwfscDeltaGLM is probably a low priority, but given that there have been no changes there in years, it should have little impact on the usage limits if/when it does get switched to a GitHub Action.
