### ISSUE TITLE
Rename functions to reflect which dataset they target (Tri, NWFSC)

### ISSUE THREAD

**Issue by andi-stephens** [nwfsc-assess/nwfscSurvey#4]
or maybe split into two packages

**Comment by taylori** [comment]
I think the ideal would be to keep the functions in a single package, but in that case, the Early West Coast (EWC) functions should be included in the package properly, not just in the Example script [Examples/EarlyWestCoastSurveyFunctions_v0.24.R](https://github.com/nwfsc-assess/nwfscSurvey/blob/master/Examples/EarlyWestCoastSurveyFunctions_v0.24.R)

**Comment by andi-stephens** [comment]
"EWC" isn't obvious enough to me, since the survey is the "Triennial".

**Comment by allanhicks** [comment]
I named it EWC because it applies to more than just Triennial. It is the
format of the data for surveys from the AFSC database.

**Comment by andi-stephens** [comment]
Aha!  Now that makes sense.

Aren't you supposed to be on Daddy duty?  Stop answering my trivial mail.
And send more pictures!

--A.

**Comment by CWetzel** [comment]
Code refresh has streamlined the code to work with all West Coast surveys. The code is currently located in the development branch waiting further testing: 

devtools::install_github("nwfsc-assess/nwfscSurvey", ref = "development", build_vignettes = TRUE)
