### ISSUE TITLE
Big refresh to all this code needed.

### ISSUE THREAD

**Issue by taylori** [nwfsc-assess/nwfscSurvey#5]
Thanks @CWetzel for volunteering to spearhead this.

**Comment by CWetzel** [comment]
Code refresh has been completed. The new code pulls directly from the data warehouse for all West Coast surveys.  The code refresh is currently located in the development branch 
(devtools::install_github("nwfsc-assess/nwfscSurvey", ref = "development", build_vignettes = TRUE) 
and will be tested further prior to merging into the main branch.
