### ISSUE TITLE
Remove empty directory during build

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscSurvey#65]
# Issue

`remotes::install_github("nwfsc-assess/nwfscSurvey")` leads to the following warning

```
Removed empty directory 'nwfscSurvey/Examples'
```
which is because of this line of code
https://github.com/nwfsc-assess/nwfscSurvey/blob/dc1b666a046076e9c9712dfc9be0ea0921f0b39e/.Rbuildignore#L5

I think the warning is happening because we specify to ignore all files in Examples but not the folder itself. 

The following code adds the folder to the .Rbuildignore file
```
> usethis::use_build_ignore("Examples")
√ Setting active project to 'C:/stockassessment/nwfscSurvey'
√ Adding '^Examples$' to '.Rbuildignore'
```

# Solution

Change "^Examples\" to "^Examples$". I can do this @chantelwetzel-noaa in main or you can add it to your 2021 branch.

**Comment by chantelwetzel-noaa** [comment]
Please go ahead and do this in the main. Thank you!
