### ISSUE TITLE
Codifying AFSC Slope Survey Sex entries

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscSurvey#67]
https://github.com/nwfsc-assess/nwfscSurvey/blob/7755b4e1dda51bbbe4210d47a675ef5bfe7d9850/R/Format.AKSlope.fn.R#L71-L74

leads to potentially some sexes being left as NA rather than all unknown sex entries as `"U"`. I wrote a helper function (`codify_sex()`) to turn various integer, character, and NA values into either "F", "M", or "U" values. I was hesitant to replace this code with it though because I wasn't sure if all NA should be "U" or not?

First, it would be good to know how many values other than, 1, 2, or 3 are in the data set? Second, everything that doesn't fall into 1:3 be coded as "U" if any values exist? Last, should we ever have `NA` values in sex?

**Comment by chantelwetzel-noaa** [comment]
I agree this should be done either by assigning everything a "U" and then assigning the males and females or a by a more robust approach. I think the AFSC Slope stuff needs to be separate or at least a switch added to the codify_sex functions since the sex assignments here are opposite compared to all other numerical sex data-sets we work with.

**Comment by kellijohnson-NOAA** [comment]
The AFSC Slope codes are not different than all other data sets though. [Page 152 of this document](https://wdfw.wa.gov/sites/default/files/publications/01754/wdfw01754.pdf), produced by WDFW, says that males are 1 for many other sampling schemes. I realize that they are different than SS3 codes for the sex column of composition data but are they actually different than a data set that we work with? And if so, which ones? @Curt-Whitmire-NOAA is there meta data somewhere for sex codes in the warehouse?

**Comment by chantelwetzel-noaa** [comment]
The sex-assignment for the AFSC Slope samples is opposite compared to what is in the done in the codify_sex() correct?

    x %in% c(1) ~ "F", 
    x %in% c(2) ~ "M",

The function is using fancy dplyr and grepls so I could be interpreting it wrong.  ;)

**Comment by kellijohnson-NOAA** [comment]
You have such an eagle eye ... I love it :heart:. I coded it backwards. So males should be 1 and females should be 2, which would match AFSC Slope and WA, OR, and CA data. Sorry for the confusion and thanks for the help. Fixed in ba48b80.

**Comment by chantelwetzel-noaa** [comment]
Perfect.  I  have a vague _memory_ that some of the numerical assignments are opposite than what we would expect, so when I saw this function my brain just connected these two ideas.  With the correction I think this would be a good approach to switch to. Thank you!

**Comment by iantaylor-NOAA** [comment]
Historical note: when I volunteered for a NWFC survey in the early 2000s, I was told that this survey was the only place where sexes were coded as 1 = female, 2 = male. I don't know how true that was at the time, but given the greater importance of female fish in so many aspects of fish population dynamics, the only explanation I can think of for a 1 = male, 2 = female coding is patriarchy. Also, why are numerical codes even being used at all any more when those databases could just be updated to use F/M/U and avoid all this confusion?
