### ISSUE TITLE
Return sci name instead of common name?

### ISSUE THREAD

**Issue by ericward-noaa** [nwfsc-assess/nwfscSurvey#71]
Right now if all the species are being pulled the default is to only return common names. It might be useful to alternatively return the scientific name, or both. Lines I'm thinking about (110-126):

https://github.com/nwfsc-assess/nwfscSurvey/blob/840931105fce610deb48cf4425892e4431208334/R/PullCatch.fn.R#L110

**Comment by chantelwetzel-noaa** [comment]
I have been thinking the same thing. I will add this change to my work in the "pull" branch.

**Comment by chantelwetzel-noaa** [comment]
Both the common and scientific names are now returned in new pull functions (pull request #80): pull_catch, pull_bio, pull_haul, pull_biological_samples. The original pull functions (PullBio, PullCatch, PullHaul) have not been modified to include this change. The current plan is to have the old and new pull functions available in the package for user continuity for the moment with the next step at some time in the future to modify the old pull function to internally call the new functions with a deprecation warning encouraging users to move to the new functions.
