### ISSUE TITLE
Units of area in expansion of biological frequency data

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscSurvey#72]
https://github.com/nwfsc-assess/nwfscSurvey/blob/bbb28ed8a8ac7fac543f0d5e5e55d2b639bb413f/R/SurveyLFs.fn.R#L68
and
https://github.com/nwfsc-assess/nwfscSurvey/blob/bbb28ed8a8ac7fac543f0d5e5e55d2b639bb413f/R/SurveyAgeAtLen.fn.R#L72
convert hectares to something by dividing by 0.01. I am guessing the end result is $km^2$ which would mean multiplying rather than dividing or dividing by 100. I could be wrong in assuming that the units of Area are $km^2$ though.

**Comment by chantelwetzel-noaa** [comment]
@kellijohnson-NOAA You are correct.  This should be area_swept_ha * 0.01 or area_swept_ha / 100

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa would you like to me to change this and do a pull request or do you want to change it? Also, I think we should change the version and add information to a NEWS.md file that tracks breaking changes like this one.

**Comment by chantelwetzel-noaa** [comment]
Let's hold off on this revision for a day or two. I went back and checked the original data warehouse calculations of expanded numbers by strata, year, and length bin and these values match what the existing code creates. I need to walk through the implications of any revision to make sure it is done correctly.

**Comment by kellijohnson-NOAA** [comment]
Sounds good. I used git blame to check if any previous revisions had been made and couldn't find any, i.e., the current calculation is what has always been used since the start of {nwfscSurvey}.

**Comment by chantelwetzel-noaa** [comment]
Fully corrected in Pull Request #80 and tagged as 2.2.1
