### ISSUE TITLE
`SexRatio.fn()` stage-2 expansion All fish sample size

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscSurvey#74]
https://github.com/nwfsc-assess/nwfscSurvey/blob/08788132b98205e9140a459eb7ca3ee38456ca70/R/SexRatio.fn.R#L104

The above code sets the sample size for all fish (i.e., "F", "M", and "U") to the expanded sample size of female fish  and not all fish. I am wondering if this is in error and should the previous line of code be the following instead?

```
TotalLjhAll = tmp$TotalLjhAll
```

Additionally, lines 94:112 could be simplified to the following:
```
out <- purrr::flatten_dfr(x)
```

**Comment by kellijohnson-NOAA** [comment]
I see this was fixed in the comps branch with 49ca13ebff0f266e4d5079cf7b68cc7eadd4d3dc. @chantelwetzel-noaa do you plan on merging this branch into master?

**Comment by chantelwetzel-noaa** [comment]
Thank you for reminding me of this fix in the comps branch.  I am currently working on a "units" branch to make sure all the units throughout the package and done correctly which will correct the length and age composition outputs.  What do you think about merging either comps into the units branch (or vice versa) since they both have corrections? Then at that point we can decide if there are additional fixes and then when done merge into the main with a new tag number.  Or is there an alternative approach we should utilize?

**Comment by kellijohnson-NOAA** [comment]
I worry that big branches with lots of changes make review hard. I would advocate for transitioning towards a fewer number of changes in a branch. Do you have any concerns about just merging comps into master? Or are there things in that branch that you do not want in master?

**Comment by chantelwetzel-noaa** [comment]
After I made that original suggestion, I opted to go rogue and just cherry-pick the commit from the "comp" branch that did this sex ratio fix into the units branch. The units branch is ready to merge into the master but will result in revisions to the output from these correction so I want to be mindful of how I do that.  Currently, I am a little uncertain on how I feel about the revisions in the "comp" branch as a whole and whether we want to move these forward. Although, I did start to be more aggressive about using @templates which I think will ultimately want but we can sift through these later at some point.

**Comment by kellijohnson-NOAA** [comment]
This sounds great @chantelwetzel-noaa. Would you like me to rename the comp branch to something else to be clear that it has templates that we might want or just leave it as is?

**Comment by chantelwetzel-noaa** [comment]
If @kellijohnson-NOAA  want to rename it that would be great. The name "wild_terrible_revamp_idea" branch comes to mind... but I suspect you have a better idea. Thanks!

**Comment by kellijohnson-NOAA** [comment]
changed to ideas-function-args and I will leave it up to you or not if you want to decrease the amount of code that is in SexRatio.fn() where the following will work in exchange for the double for loop
```
out <- purrr::flatten_dfr(x)
```

Thanks for the helpful discussion @chantelwetzel-noaa ❤️
