### ISSUE TITLE
Sex ratio if sexRatioStage == 2

### ISSUE THREAD

**Issue by kellijohnson** [nwfsc-assess/nwfscSurvey#8]
The function https://github.com/nwfsc-assess/nwfscSurvey/blob/62e41125d12a27e3ad9b918e6563a8056c84c9f6/R/SexRatio.fn.R#L72
fails if `i` is at the end of the vector because the object `upper` becomes `NA`. I am not sure how best to fix it, should it just be based on `lower` rather than a combination of `lower` and `upper`. The same fix should be done if `i == 1` as well.

**Comment by kellijohnson** [comment]
Also, shouldn't we be taking the mean of two values 
```
sexRatio[i] <- mean(c(lower, upper))
```
rather than the mean of the sum?
```
sexRatio[i] <- mean(lower + upper)
```

**Comment by kellijohnson** [comment]
Shoot, one more thing. The `print` statement that comes directly after this will only print the first entry because `...` refers to extra arguments not extra objects to print. Instead we should use `message` or something along those lines because users can turn `messages` and `warnings` on and off, whereas `cat` statements are hard to control the output of. E.g.,
```
message("sex ratio for length ", x$LENGTH[i], " was changed to ", sexRatio[i])
```

**Comment by CWetzel** [comment]
The SexRatio.fn has been updated to deal with the issues identified by @kellijohnson and the print statements have been changed to messages.
